resources:
  repositories:
    - repository: VulnerableCode
      type: git
      name: JavaVulnerableLabE
      ref: master

stages:
- stage: Deploy
  pool: 
    name: Default
  jobs:
  - job: Job
    steps:
    - checkout: VulnerableCode  
    - task: Checkmarx-Prerelease.cxsast.cx-scan-task.Application security testing@2022
      displayName: 'Application security testing'
      inputs:
        projectName: 'YML SAST'
        syncMode: true
        enableProxy: false
        proxyUrl: ''
        enableSastScan: true
        CheckmarxService: 9.4
        sastProxyUrl: ''
        preset: Android
        customPreset: 'All'
        engineConfigId: 
        fullTeamName: /CxServer
        sastCaChainFilePath: ''
        overrideProjectSettings: false
        scanTimeout: 5
        customfields: 'Key1:Value1'
        denyProject: false
        comment: 'Generating YAML File'
        generatePDFReport: true
        vulnerabilityThreshold: true
        failBuildForNewVulnerabilitiesEnabled: true
        failBuildForNewVulnerabilitiesSeverity: MEDIUM
        high: 10
        medium: 10
        low: 10
        enablePolicyViolations: false
        avoidDuplicateScans: false