steps:
- task: Application security testing@2022
  inputs:
    projectName: 'Sprint 11'
    enableProxy: false
    enableSastScan: true
    CheckmarxService: '9.4'
    preset: 'Android'
    customPreset: 'All'
    fullTeamName: '/CxServer'
    fullScansScheduled: true
    fullScanCycle: '5'
    fileExtension: 'cvs, .svn, .hg , .git, .bzr, bin , obj,  backup, .idea, node_modules'
    scanTimeout: '5'
    projectcustomfields: 'Key1:Value1'
    customfields: 'Key1:Value1'
    comment: 'Generating YAML File'
    postScanAction: 'Trial'
    generatePDFReport: true
    vulnerabilityThreshold: true
    failBuildForNewVulnerabilitiesEnabled: true
    failBuildForNewVulnerabilitiesSeverity: 'MEDIUM'
    high: '10'
    medium: '10'
    low: '10'
    enableDependencyScan: false